/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.spg.unab;

/**
 *
 * @author Alex
 */
public class retiro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(retiro.class.getName());

    /**
     * Creates new form retiro
     */
    public retiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCuentadeAhorros = new javax.swing.JButton();
        btnSalirInicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCuentadeAhorros.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnCuentadeAhorros.setForeground(new java.awt.Color(255, 255, 255));
        btnCuentadeAhorros.setText("CUENTA DE AHORROS");
        btnCuentadeAhorros.setBorderPainted(false);
        btnCuentadeAhorros.setContentAreaFilled(false);
        btnCuentadeAhorros.setFocusPainted(false);
        btnCuentadeAhorros.addActionListener(this::btnCuentadeAhorrosActionPerformed);
        jPanel1.add(btnCuentadeAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 520, 600, 110));

        btnSalirInicio.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnSalirInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirInicio.setText("CANCELAR");
        btnSalirInicio.setBorderPainted(false);
        btnSalirInicio.setContentAreaFilled(false);
        btnSalirInicio.setFocusPainted(false);
        btnSalirInicio.addActionListener(this::btnSalirInicioActionPerformed);
        jPanel1.add(btnSalirInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 840, 340, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECCIONE UNA OPCIÓN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/RETIRO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 2680, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirInicioActionPerformed
         inicio ventanaInicio = new inicio();
    ventanaInicio.setVisible(true);
    this.dispose();    
    }//GEN-LAST:event_btnSalirInicioActionPerformed

    private void btnCuentadeAhorrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentadeAhorrosActionPerformed
        cantidadaretirar ventanaRetiro = new cantidadaretirar();
    ventanaRetiro.setVisible(true);
    this.dispose();    
    }//GEN-LAST:event_btnCuentadeAhorrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new retiro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuentadeAhorros;
    private javax.swing.JButton btnSalirInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
