/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.spg.unab;

/**
 *
 * @author Alex
 */
public class retiroproceder extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(retiroproceder.class.getName());

    /**
     * Creates new form retiroproceder
     */
    public retiroproceder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCantidadNoCorrecta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCantidadSiCorrecta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCantidadNoCorrecta.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnCantidadNoCorrecta.setForeground(new java.awt.Color(255, 255, 255));
        btnCantidadNoCorrecta.setText("NO");
        btnCantidadNoCorrecta.setBorderPainted(false);
        btnCantidadNoCorrecta.setContentAreaFilled(false);
        btnCantidadNoCorrecta.setFocusPainted(false);
        btnCantidadNoCorrecta.addActionListener(this::btnCantidadNoCorrectaActionPerformed);
        jPanel1.add(btnCantidadNoCorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 800, 150, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿ES CORRECTA LA CANTIDAD A RETIRAR?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        btnCantidadSiCorrecta.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnCantidadSiCorrecta.setForeground(new java.awt.Color(255, 255, 255));
        btnCantidadSiCorrecta.setText("SÍ");
        btnCantidadSiCorrecta.setBorderPainted(false);
        btnCantidadSiCorrecta.setContentAreaFilled(false);
        btnCantidadSiCorrecta.setFocusPainted(false);
        btnCantidadSiCorrecta.addActionListener(this::btnCantidadSiCorrectaActionPerformed);
        jPanel1.add(btnCantidadSiCorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 830, 150, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PROCEDERRETIRO.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 2680, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCantidadNoCorrectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadNoCorrectaActionPerformed
    cantidadaretirar ventanaCantidad = new cantidadaretirar ();
    ventanaCantidad.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_btnCantidadNoCorrectaActionPerformed

    private void btnCantidadSiCorrectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadSiCorrectaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadSiCorrectaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new retiroproceder().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCantidadNoCorrecta;
    private javax.swing.JButton btnCantidadSiCorrecta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
