/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.spg.unab;

/**
 *
 * @author Alex
 */
public class transaccion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(transaccion.class.getName());

    /**
     * Creates new form transaccion
     */
    public transaccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRetiros = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnConsultarSaldo = new javax.swing.JButton();
        btnSalirTransaccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRetiros.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnRetiros.setForeground(new java.awt.Color(255, 255, 255));
        btnRetiros.setText("RETIROS");
        btnRetiros.setBorderPainted(false);
        btnRetiros.setContentAreaFilled(false);
        btnRetiros.setFocusPainted(false);
        btnRetiros.addActionListener(this::btnRetirosActionPerformed);
        jPanel1.add(btnRetiros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 520, 260, 110));

        btnDeposito.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnDeposito.setForeground(new java.awt.Color(255, 255, 255));
        btnDeposito.setText("DEPOSITO");
        btnDeposito.setBorderPainted(false);
        btnDeposito.setContentAreaFilled(false);
        btnDeposito.setFocusPainted(false);
        jPanel1.add(btnDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 840, 300, 110));

        btnConsultarSaldo.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnConsultarSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarSaldo.setText("CONSULTAR SALDO");
        btnConsultarSaldo.setBorderPainted(false);
        btnConsultarSaldo.setContentAreaFilled(false);
        btnConsultarSaldo.setFocusPainted(false);
        jPanel1.add(btnConsultarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 540, 110));

        btnSalirTransaccion.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnSalirTransaccion.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirTransaccion.setText("SALIR");
        btnSalirTransaccion.setBorderPainted(false);
        btnSalirTransaccion.setContentAreaFilled(false);
        btnSalirTransaccion.setFocusPainted(false);
        jPanel1.add(btnSalirTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 820, 190, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECCIONE SU TRANSACCIÓN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TRANSACCION.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 2680, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirosActionPerformed
       retiro ventanaRetiro = new retiro();
    ventanaRetiro.setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_btnRetirosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new transaccion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarSaldo;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnRetiros;
    private javax.swing.JButton btnSalirTransaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
